# my-first-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: webserver
spec:
  containers:
  - name: pod-demo
    image: guanyebo/nodejs-web:v2.0
    ports:
    - containerPort: 3000
